application: outernet-tekhenu
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: conf/robots.txt
  upload: conf/robots.txt

- url: /favicon.ico
  static_files: tekhenu/static/img/favicon.ico
  upload: tekhenu/static/img/favicon.ico
  secure: always

- url: /static/img/(.*)
  static_files: tekhenu/static/img/\1
  upload: tekhenu/static/img/(.*\.(gif|png|jpg))
  secure: always

- url: /static/css/(.*)
  static_files: tekhenu/static/css/\1
  upload: tekhenu/static/css/(.*\.(css|woff|eot|ttf|svg))
  secure: always

- url: /static/js/(.*)
  static_files: tekhenu/static/js/\1
  upload: tekhenu/static/js/(.*\.js)
  secure: always

# This URL is only used by admins.
- url: /\w+/broadcast.*
  script: tekhenu.main.app
  secure: always
  login: admin

- url: /.*
  script: tekhenu.main.app
  secure: always

skip_files:
- ^\.git.*$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.sw[op]$
- ^README.md$
- ^/scss.*
- ^/.sass-cache.*
