application: outernet-tekhenu
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always

- url: /static/img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  secure: always

- url: /static/css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*\.(css|woff|eot|ttf|svg))
  secure: always

- url: /static/js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
  secure: always

- url: /.*
  script: tekhenu.main.app
  secure: always

skip_files:
- ^\.git.*$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.sw[op]$
- ^README.md$
- ^static\/scss.*
- ^static\/.sass-cache.*
